services:
  - type: web
    name: dilakesh-portfolio-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5050
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: dilakesh756@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
